---
abstract: 'automatic class short names'
author:
  - 'Aaron Cohen <aarondcohen@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker::CPANfile: 0.05
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Role-Nameable
no_index:
  directory:
    - t
    - inc
requires:
  ExtUtils::MakeMaker: 0
  ExtUtils::MakeMaker::CPANfile: 0
  MooseX::Role::Parameterized: 0
  Test::Most: 0
resources:
  bugtracker: http://github.com/aarondcohen/perl-moosex-role-nameable/issues
  homepage: http://github.com/aarondcohen/perl-moosex-role-nameable
  repository: git://github.com/aarondcohen/perl-moosex-role-nameable.git
version: 1.01
